name: Client
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/client.yaml'
      - 'apps/client/**'
  workflow_dispatch:

concurrency:
  group: client-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Client
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "NEXT_PUBLIC_ENDPOINT=https://massage-api.lico.moe" >> .env
          echo "NEXTAUTH_URL=https://massage.lico.moe" >> .env
          echo "NEXTAUTH_SECRET={{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "NEXT_PUBLIC_APP_ENV=production" >> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/client/Dockerfile
          push: true
          tags: ghcr.io/gusb3ll/massage/client:latest
          cache-from: type=registry,ref=ghcr.io/gusb3ll/massage/client
          cache-to: type=inline

      - name: Redeploy client
        run: kubectl rollout restart deployment client --namespace=massage
