name: Server
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/server.yaml'
      - 'apps/server/**'
      - 'packages/**'
  workflow_dispatch:

concurrency:
  group: server-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "ENTROPY=XnE3iXA23aVI+JB6NDNfuXCQw052e4VCEETdGaSCXVo=" >> .env
          echo "DATABASE_URL=postgresql://local:local@103.216.158.158:5432/massage?schema=public" >> .env
          echo "MAILER_HOST=smtp.resend.com" >> .env
          echo "MAILER_USERNAME=resend" >> .env
          echo "MAILER_PASSWORD=re_NoNjAiBD_Mb4tJmB6LVMBRMamHLpMFECB" >> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/server/Dockerfile
          push: true
          tags: ghcr.io/gusb3ll/massage/server:latest
          cache-from: type=registry,ref=ghcr.io/gusb3ll/massage/server
          cache-to: type=inline

      # - name: Redeploy server
      #   run: kubectl rollout restart deployment server --namespace=massage
